server:
  port: 8085
  servlet:
    context-path: /
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/pink?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true # 开启文件上传
      file-size-threshold: 2KB # 文件写入磁盘的阈值
      max-file-size: 100MB
      max-request-size: 215MB # 最大请求值大小
  ai:
    openai:
      base-url: https://api.siliconflow.cn/
      api-key: sk-dobvageguyfakmwdiwkjiwjtogauaxrwioebmckfiqpptchs
      chat:
        options:
          model: deepseek-ai/DeepSeek-R1
  # qq邮箱配置
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: siocbzuocofdbeif
    port: 465
    username: 821285060@qq.com
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true


logging:
  level:
    org:
      springframework:
        ai:
          mail: DEBUG
          chat:
            client:
              advisor: DEBUG
    jakarta.mail: DEBUG

mybatis:
  mapper-locations: classpath:mybatis/mapper/*/*.xml
  type-aliases-package: com.work.pinkweb.Entity

# APPID
alipay:
  appId: 2021000146658276
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCu2rs+kUwvCpTKJ9LZrI/izeGPTrfrk0l9Tm8uLIk+l3lAAkclT6jnBa6sBK8Gen/yPeCfW1ydLghLhO3mfhu9hpN+mRxRH2XCB5tLmJKDFa+Mdqrkp6RZfX+kGAH7jv3jrIEwaBn2qL5C1KRv05aMIHp+7EVqz78Y4laTtAdV/gZNgh4nw6rTOx8ecskm0lz5yzwpRkW0wqGKuO0iUdFKAoAVVEWFfIVAUZdA1HsWM58pR67KqOOu1ZmEva16kbmejq9mBwa/JTw+cURmcafpRrsB2is/6GoHHw9LIO+aQ5qcpXh7LhrE4FbRKj9oa97ZM4ERzuzfGvAWjiddqzc9AgMBAAECggEBAKq81v3fbx64HFXR0SfQQqfbFZeT7C/SIH6FKjdSMam2yyTflI0wXeNIPymlYSrYTztBhKbW1XZ9zoe/g3YASiIk2L1T0Ly+BeUS/Gcy0k3BzStBbNndgLQJwat/7d+v3uaEOZoE7OVYHICxlufDGkw2IqbxG0+TECzCRnvv3QHva3sPgZaJ4mNgFmage2DOhn0emZsONZBSJi3QuKDk3ZtXdd+oxZGqICXu4Ra7B7Ut/jVbeTiYF3y/YonokXzueV8huMjnIe/iB9oDcf3r3Ch9lt82SlVz+f2Meb2+StRnE3JV5YTECGk0imsVQT3uu2r+Uv2J1qp1jmVULbyN4tkCgYEA8WTPzjQcgVp6h/gIZTJL1GlBtxKCTnK2ZkWlCfO8YAkNlm/FxSSEWEJzo7zJK82c/wOq11zEUlI09+kVJIG4ae1ssbJ6bZn7DqvvSG1nRXrDgGHlL2fnPvYbEyhxoJh9iXmimmP+miO/ABbneyEN6thj0NFd+jsKnB2qHm9NhysCgYEAuW85poDyxfw+I5u+OOfuxy4NNZY781wJDaAtumM/KQnDZCRHJ2SH7xj+UXREJz0sKXt+ddoS4Da/mNeQQ2AjglByhNbrvWJvQ/tyynNhcLpF0VsS6IwHOBHQU6/TbgHOWzfS4zt+qDx2AyEWdxtWx3CprU7Y5IrYMweT7VdzBzcCgYAk2CFLtPKA3+GB7V7Cq2mdky8/lSikdqfWdlzZZwVilx8mzgqeq5MzsXjbDg6ai/ihh9rEolkow3loOYBLoS0XpfCIMtiy7+S8+Ys9P82ackFyz/5ePPqzxnaddvfY7k2C9TjXXdnXhws5JUXRqlrodHzPu5Ufg3F8IJ79pDluHwKBgCCNjxBU2Mm682mq4KT6ymc7BWSf4Bxjzs8OjJiI7cCVjzCYUclvk5F80MCZ6ZD94y/RFy03QFMOKWp6hT/es70fxErfs/jGPAQyMz+pK7TvbmxHUbVzR50nO2xFlJdeR8ypqyLrAdwk6Q65k0kLiptugssC6X6NhVDIBscGsBHXAoGAUBjCWRjnZ6CBwvSCq/347NYkN5Wd9ozt6M/IiTUgTLQc6XhqTeffZVwodwKvtVvKEQbem66YaiO+6U0+2zV5jqaqsY0pkSGq9GGbBOy+AY1xolEqEos9iP6OSzZCQECzwp6tYTf3AOl5S+qy33NdNLlX0R9ffUxUghCFPrrVYvU=
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArtq7PpFMLwqUyifS2ayP4s3hj06365NJfU5vLiyJPpd5QAJHJU+o5wWurASvBnp/8j3gn1tcnS4IS4Tt5n4bvYaTfpkcUR9lwgebS5iSgxWvjHaq5KekWX1/pBgB+47946yBMGgZ9qi+QtSkb9OWjCB6fuxFas+/GOJWk7QHVf4GTYIeJ8Oq0zsfHnLJJtJc+cs8KUZFtMKhirjtIlHRSgKAFVRFhXyFQFGXQNR7FjOfKUeuyqjjrtWZhL2tepG5no6vZgcGvyU8PnFEZnGn6Ua7AdorP+hqBx8PSyDvmkOanKV4ey4axOBW0So/aGve2TOBEc7s3xrwFo4nXas3PQIDAQAB
  notifyUrl: http://ek7hhz.natappfree.cc/order/alipay
  returnUrl: http://localhost:8080/index/apply_profile/#/paySuccess
  signType: RSA2
  charset: UTF-8
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  logPath: "D:\\"