server:
  port: 8085
  servlet:
    context-path: /
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/pink?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true # 开启文件上传
      file-size-threshold: 2KB # 文件写入磁盘的阈值
      max-file-size: 100MB
      max-request-size: 215MB # 最大请求值大小
  ai:
    openai:
      base-url: https://api.siliconflow.cn/
      api-key: sk-dobvageguyfakmwdiwkjiwjtogauaxrwioebmckfiqpptchs
      chat:
        options:
          model: deepseek-ai/DeepSeek-R1
  # qq邮箱配置
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: siocbzuocofdbeif
    port: 465
    username: 821285060@qq.com
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true


logging:
  level:
    org:
      springframework:
        ai:
          mail: DEBUG
          chat:
            client:
              advisor: DEBUG
    jakarta.mail: DEBUG

mybatis:
  mapper-locations: classpath:mybatis/mapper/*/*.xml
  type-aliases-package: com.work.pinkweb.Entity